const DAYS=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];
const C=window.TIBIA_CATALOGS||{};
const BOSSES=C.bosses||[{name:'Grand Master Oberon',image_url:'https://static.tibia.com/images/library/grandmasteroberon.gif'},{name:'Scarlett Etzel',image_url:'https://static.tibia.com/images/library/scarlettetzelstill.gif'},{name:'Drume',image_url:'https://static.tibia.com/images/library/drume.gif'}];
const CREATURES=C.creatures||[{name:'Adult Goannas',image_url:'https://static.tibia.com/images/library/adultgoanna.gif'},{name:'Young Goannas',image_url:'https://static.tibia.com/images/library/younggoanna.gif'}];
const HUNTS=C.hunts||['Goannas — Cobra Bastion','Gnomprona','Nagas — Marapur','Cobras — Cobra Bastion'];
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
let day=new Date().getDay(),editingTemplate=null,editingDay=null,pickerMode='bosses',draft={bosses:[],monsters:[],locations:[]},tempBestiary={},auth=loadAuth(),currentUser=null;
const img=(type,name)=>{const list=type==='bosses'?BOSSES:CREATURES;return (list.find(x=>x.name===name)||{}).image_url||'https://www.tibiawiki.com.br/wiki/Special:Redirect/file/'+encodeURIComponent(name.replaceAll(' ','_'))+'.gif'};
const makeDays=mode=>DAYS.map((_,i)=>mode==='gt'?{kind:i?'Bosses':'Livre',title:i?'GT/GD em party':'Descanso / ajuste',time:'20:45',desc:i?'Rodada fixa de bosses em equipe.':'Dia aberto para combinar reposição.',bosses:i?['The Time Guardian','The Last Lore Keeper','Lady Tenebris']:[],monsters:[],locations:i?['Ferumbras Ascendant Seals']:['A definir'],hunt:i?'GT/GD em party':'A definir',refills:0,notes:'Checar acesso e cooldown antes de sair'}:i===1?{kind:'Misto',title:'Bosses + Goannas',time:'20:30',desc:'Limpar bosses de item e fechar com uma hunt curta.',bosses:['Grand Master Oberon','Scarlett Etzel','Drume'],monsters:['Adult Goannas','Young Goannas'],locations:['Goannas — Cobra Bastion'],hunt:'Goannas — Cobra Bastion',refills:1,notes:'Supplies para 1h • Imbuements prontos'}:{kind:i%2?'Bosses':'Livre',title:i%2?'Rodada de bosses':'Noite livre',time:'21:00',desc:'Ajustar conforme a party online.',bosses:i%2?['Grand Master Oberon','Scarlett Etzel']:[],monsters:[],locations:['A definir'],hunt:'A definir',refills:0,notes:'Pode ser alterado antes da call'});
const defaults={version:4,players:['Murilo','Rafael','Bruno','Caio'],current:'Murilo',activeTemplateId:'bosses_item',templates:[{id:'bosses_item',mode:'recorrente',name:'BOSSES DE ITEM',description:'Semana focada em bosses diários e chances de drop raro.',participants:['Murilo','Rafael','Bruno','Caio'],days:makeDays('boss')},{id:'gt_gd',mode:'recorrente',name:'GT / GD',description:'Rotina para focar Grave Danger e Forgotten Knowledge/GT conforme disponibilidade.',participants:['Murilo','Rafael','Bruno','Caio'],days:makeDays('gt')}],attendance:{},drops:[],bestiary:{}};
const clone=x=>structuredClone?structuredClone(x):JSON.parse(JSON.stringify(x));
function normalizeDay(d){return {...{kind:'Misto',title:'A definir',time:'21:00',desc:'',bosses:[],monsters:[],locations:[],hunt:'A definir',refills:0,notes:''},...d,bosses:d?.bosses||[],monsters:d?.monsters||[],locations:d?.locations||(d?.hunt?[d.hunt]:[])}}
function normalizeTemplate(t){t.mode=t.mode||'recorrente';t.days=(t.days||makeDays('boss')).map(normalizeDay);t.participants=t.participants||[];return t}
function migrate(data){if(!data)return null;if(data.version>=3){data.version=4;data.templates=data.templates.map(normalizeTemplate);return data}const migrated={...clone(defaults),players:data.players||defaults.players,current:data.current||defaults.current,attendance:data.attendance||{},drops:data.drops||[],bestiary:{}};if(data.templates)migrated.templates=data.templates.map(normalizeTemplate);else if(data.routines)migrated.templates=[{...clone(defaults.templates[0]),days:data.routines.map(normalizeDay)}];return migrated}
function load(){try{const encoded=new URLSearchParams(location.hash.slice(1)).get('agenda');if(encoded){const data=migrate(JSON.parse(decodeURIComponent(escape(atob(encoded)))));localStorage.guildAgendaV3=JSON.stringify(data);history.replaceState(0,'',location.pathname);return data}return migrate(JSON.parse(localStorage.guildAgendaV3||localStorage.guildAgendaV2||localStorage.guildAgenda||'null'))||clone(defaults)}catch{return clone(defaults)}}
let state=load();
function save(){localStorage.guildAgendaV3=JSON.stringify(state)}
function modeLabel(t){return (t.mode||'recorrente')==='especifica'?'SEMANA ESPECÍFICA':'ROTINA RECORRENTE'}
function active(){return normalizeTemplate(state.templates.find(t=>t.id===state.activeTemplateId)||state.templates[0])}
function plan(){const t=active();t.days[day]=normalizeDay(t.days[day]);return t.days[day]}
function key(player=state.current){return `${active().id}:${day}:${player}`}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2300)}
function chips(arr,type){return arr.length?arr.map(x=>`<div class="boss"><img src="${img(type,x)}" onerror="this.style.display='none'"><b>${x}</b></div>`).join(''):'<span class="sub">Nada selecionado.</span>'}
function render(){const t=active(),p=plan();$('nav').innerHTML=DAYS.map((d,i)=>`<button class="${i===day?'active':''}" onclick="day=${i};render()">${d}<small>${normalizeDay(t.days[i]).kind}</small></button>`).join('');$('templateSelect').innerHTML=state.templates.map(x=>`<option value="${x.id}" ${x.id===t.id?'selected':''}>${x.name}</option>`).join('');$('player').innerHTML=state.players.map(x=>`<option ${x===state.current?'selected':''}>${x}</option>`).join('');$('routineName').textContent=t.name;$('routineDesc').textContent=t.description;$('routineMode').textContent=modeLabel(t);$('day').textContent=DAYS[day];$('title').textContent=p.title;$('kind').textContent=p.kind;$('time').textContent='▷ '+p.time;$('desc').textContent=p.desc||'Sem descrição.';$('bossCount').textContent=` • ${p.bosses.length} alvo(s)`;$('monsterCount').textContent=` • ${p.monsters.length} criatura(s)`;$('bossList').innerHTML=chips(p.bosses,'bosses');$('monsterList').innerHTML=chips(p.monsters,'monsters');$('locationList').innerHTML=p.locations.length?p.locations.map(x=>`<span class="huntchip">${x}</span>`).join(''):'<span class="sub">Nenhum local selecionado.</span>';$('hunt').textContent=p.hunt||p.locations[0]||'A definir';$('notes').textContent=p.notes||'Sem observações';$('refills').textContent=p.refills||0;$('next').textContent=DAYS[day]+' • '+p.time;$('nextName').textContent=t.name;const absence=state.attendance[key()];$('notice').hidden=!absence;$('notice').textContent=absence?`Sua ausência está registrada: “${absence.reason}”`:'';$('members').innerHTML=t.participants.map(x=>{const a=state.attendance[`${t.id}:${day}:${x}`];return `<div class="member"><div class="avatar">${x.slice(0,2).toUpperCase()}</div><div><b>${x}</b><small>${a?a.reason:'Confirmado na rotina'}</small></div><span class="status ${a?'no':''}">${a?'NÃO VAI':'VAI'}</span></div>`}).join('')||'<p class="sub">Nenhum participante definido.</p>';renderDrops();renderBestiary();renderStats()}
function renderDrops(){const t=active(),drops=state.drops.filter(d=>d.templateId===t.id);$('drops').innerHTML=drops.length?drops.slice().reverse().map(d=>`<div class="drop"><b>${d.item}</b><span>${DAYS[d.day]} • ${d.by} • ${d.source||'origem não informada'}</span><small>${new Date(d.date).toLocaleDateString('pt-BR')}${d.note?' — '+d.note:''}</small></div>`).join(''):'<p class="sub">Nenhum drop registrado nessa rotina ainda.</p>'}
function routineBosses(){return [...new Set(active().days.flatMap(d=>normalizeDay(d).bosses))]}
function getBestiary(){const raw=state.bestiary[active().id]||{};if(Object.values(raw)[0]&&typeof Object.values(raw)[0]==='object')return raw;return {}}
function renderBestiary(){const map=getBestiary(),bosses=routineBosses();$('bestiary').innerHTML=active().participants.map(p=>`<div class="bestiary"><b>${p}</b><span>${bosses.length?bosses.map(b=>`${b}: ${(map[p]||{})[b]||0}`).join(' • '):'Adicione bosses na rotina para contar.'}</span></div>`).join('')||'<p class="sub">Defina participantes para registrar o bostiary.</p>'}
function renderStats(){const t=active(),drops=state.drops.filter(d=>d.templateId===t.id),runs=t.days.filter(d=>normalizeDay(d).kind!=='Livre').length||1,items={};drops.forEach(d=>items[d.item]=(items[d.item]||0)+1);$('stats').innerHTML=`<b>${drops.length}</b><span>drops registrados</span><b>${(drops.length/runs).toFixed(2)}</b><span>drops por dia ativo da rotina</span><small>${Object.entries(items).map(([k,v])=>`${k}: ${v}`).join(' • ')||'Sem itens para medir frequência ainda.'}</small>`}
$('templateSelect').onchange=e=>{state.activeTemplateId=e.target.value;save();render();toast('Rotina selecionada')};$('player').onchange=e=>{state.current=e.target.value;save();render()};$('share').onclick=async()=>{const u=location.origin+location.pathname+'#agenda='+btoa(unescape(encodeURIComponent(JSON.stringify(state))));try{await navigator.clipboard.writeText(u);toast('Link copiado!')}catch{prompt('Copie o link:',u)}};
$('newTemplate').onclick=()=>openTemplate();$('editTemplate').onclick=()=>openTemplate(active());function openTemplate(t){editingTemplate=t||null;$('tplTitle').textContent=t?'Editar rotina salva':'Criar rotina salva';$('tplName').value=t?.name||'Nova rotina';$('tplDesc').value=t?.description||'';$('tplMode').value=t?.mode||'recorrente';$('tplParticipants').value=(t?.participants||state.players).join(', ');$('templateDlg').showModal()}
$('deleteTemplate').onclick=()=>{const t=active();if(state.templates.length<=1){toast('Mantenha ao menos uma rotina');return}if(!confirm(`Excluir a rotina "${t.name}"? Drops, presença e bostiary ligados a ela também saem deste navegador.`))return;state.templates=state.templates.filter(x=>x.id!==t.id);delete state.bestiary[t.id];state.drops=state.drops.filter(d=>d.templateId!==t.id);Object.keys(state.attendance).filter(k=>k.startsWith(t.id+':')).forEach(k=>delete state.attendance[k]);state.activeTemplateId=state.templates[0].id;save();render();toast('Rotina excluída')};
$('templateForm').onsubmit=e=>{e.preventDefault();const participants=$('tplParticipants').value.split(',').map(x=>x.trim()).filter(Boolean);if(editingTemplate){editingTemplate.name=$('tplName').value.trim();editingTemplate.description=$('tplDesc').value.trim();editingTemplate.mode=$('tplMode').value;editingTemplate.participants=participants}else{const base=clone(active());base.id=uid();base.name=$('tplName').value.trim();base.description=$('tplDesc').value.trim();base.mode=$('tplMode').value;base.participants=participants;state.templates.push(base);state.activeTemplateId=base.id}save();render();$('templateDlg').close();toast('Rotina salva')};$('duplicateTemplate').onclick=()=>{const base=clone(active());base.id=uid();base.name+=' — cópia';state.templates.push(base);state.activeTemplateId=base.id;save();render();toast('Rotina duplicada')};
$('edit').onclick=()=>{const p=plan();editingDay=day;draft={bosses:[...p.bosses],monsters:[...p.monsters],locations:[...p.locations]};$('fKind').value=p.kind;$('fTitle').value=p.title;$('fTime').value=p.time;$('fDesc').value=p.desc;$('fHunt').value=p.hunt;$('fNotes').value=p.notes;$('fRefills').value=p.refills;renderDraft();$('routineDlg').showModal()};
function renderDraft(){$('draftBosses').innerHTML=draft.bosses.map(x=>`<span class="chip">${x}</span>`).join('')||'<span class="chip">Nenhum</span>';$('draftMonsters').innerHTML=draft.monsters.map(x=>`<span class="chip">${x}</span>`).join('')||'<span class="chip">Nenhum</span>';$('draftLocations').innerHTML=draft.locations.map(x=>`<span class="chip">${x}</span>`).join('')||'<span class="chip">Nenhum</span>'}
$('routineForm').onsubmit=e=>{e.preventDefault();active().days[editingDay]={kind:$('fKind').value,title:$('fTitle').value,time:$('fTime').value,desc:$('fDesc').value,hunt:$('fHunt').value||draft.locations[0]||'A definir',notes:$('fNotes').value,refills:+$('fRefills').value,bosses:[...draft.bosses],monsters:[...draft.monsters],locations:[...draft.locations]};save();render();$('routineDlg').close();toast('Dia salvo')};
function listForMode(){return pickerMode==='bosses'?BOSSES:pickerMode==='monsters'?CREATURES:HUNTS.map(name=>({name}))}
function openPicker(mode){pickerMode=mode;$('pickerTitle').textContent=mode==='bosses'?'Escolha os bosses':mode==='monsters'?'Escolha monstros/criaturas':'Escolha locais de hunt';$('pickerSearch').value='';renderPicker();$('pickerDlg').showModal()}
function renderPicker(){const q=$('pickerSearch').value.toLowerCase(),selected=draft[pickerMode];$('pickerCount').textContent=selected.length+' selecionado(s)';$('pickerCatalog').innerHTML=listForMode().filter(x=>x.name.toLowerCase().includes(q)).slice(0,260).map(x=>`<button class="option ${selected.includes(x.name)?'on':''}" onclick="toggleEntity('${x.name.replaceAll("'","\\'")}')">${x.image_url?`<img src="${x.image_url}" onerror="this.style.opacity='.15'">`:''}<b>${x.name}</b></button>`).join('')}
window.toggleEntity=name=>{const arr=draft[pickerMode];arr.includes(name)?draft[pickerMode]=arr.filter(x=>x!==name):arr.push(name);renderPicker();renderDraft()};
$('chooseBosses').onclick=()=>openPicker('bosses');$('chooseMonsters').onclick=()=>openPicker('monsters');$('chooseLocations').onclick=()=>openPicker('locations');$('pickerSearch').oninput=renderPicker;$('addEntity').onclick=()=>{const x=$('manualEntity').value.trim();if(x&&!draft[pickerMode].includes(x))draft[pickerMode].push(x);$('manualEntity').value='';renderPicker();renderDraft()};$('confirmPicker').onclick=()=>$('pickerDlg').close();
$('absent').onclick=()=>{$('reason').value=state.attendance[key()]?.reason||'';$('absenceDlg').showModal()};$('absenceForm').onsubmit=e=>{e.preventDefault();state.attendance[key()]={reason:$('reason').value.trim()};save();render();$('absenceDlg').close();toast('Ausência registrada')};
$('manage').onclick=()=>{$('editor').innerHTML=state.players.map((x,i)=>`<div class="manual"><input value="${x}"><button class="btn red" type="button" onclick="state.players.splice(${i},1);manage.click()">×</button></div>`).join('');$('membersDlg').showModal()};$('addPlayer').onclick=()=>{state.players.push('Novo jogador');$('membersDlg').close();$('manage').click()};$('membersForm').onsubmit=e=>{e.preventDefault();state.players=[...$('editor').querySelectorAll('input')].map(x=>x.value.trim()).filter(Boolean);if(!state.players.includes(state.current))state.current=state.players[0]||'';active().participants=active().participants.filter(x=>state.players.includes(x));save();render();$('membersDlg').close();toast('Grupo atualizado')};
$('addDrop').onclick=()=>{$('dropBy').innerHTML=active().participants.map(x=>`<option>${x}</option>`).join('');$('dropSource').value=plan().bosses[0]||plan().locations[0]||plan().hunt||'';$('dropItem').value='';$('dropNote').value='';$('dropDlg').showModal()};$('dropForm').onsubmit=e=>{e.preventDefault();state.drops.push({id:uid(),date:new Date().toISOString(),templateId:active().id,day,item:$('dropItem').value.trim(),by:$('dropBy').value,source:$('dropSource').value.trim(),note:$('dropNote').value.trim()});save();render();$('dropDlg').close();toast('Drop registrado')};
$('editBestiary').onclick=()=>{tempBestiary=clone(getBestiary());const bosses=routineBosses();$('bestiaryEditor').innerHTML=bosses.length?active().participants.map(p=>`<div class="bestiaryBlock"><h3>${p}</h3>${bosses.map(b=>{const v=(tempBestiary[p]||{})[b]||0;return `<div class="counter"><span>${b}</span><button type="button" onclick="bestiaryInc('${p.replaceAll("'","\\'")}','${b.replaceAll("'","\\'")}',-1)">−</button><output>${v}</output><button type="button" onclick="bestiaryInc('${p.replaceAll("'","\\'")}','${b.replaceAll("'","\\'")}',1)">+</button></div>`}).join('')}</div>`).join(''):'<p class="sub">Adicione bosses nos dias da rotina para contar bostiary.</p>';$('bestiaryDlg').showModal()};
window.bestiaryInc=(p,b,delta)=>{tempBestiary[p]=tempBestiary[p]||{};tempBestiary[p][b]=Math.max(0,(tempBestiary[p][b]||0)+delta);$('bestiaryEditor').querySelectorAll('.counter').forEach(row=>{if(row.children[0].textContent===b&&row.closest('.bestiaryBlock')?.querySelector('h3')?.textContent===p)row.querySelector('output').textContent=tempBestiary[p][b]})};
$('bestiaryForm').onsubmit=e=>{e.preventDefault();state.bestiary[active().id]=tempBestiary;save();render();$('bestiaryDlg').close();toast('Bostiary salvo')};
function loadAuth(){try{return JSON.parse(localStorage.guildAgendaAuth||'{"users":[],"session":null}')}catch{return {users:[],session:null}}}
async function passHash(password){if(crypto.subtle){const bytes=new TextEncoder().encode(password),hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}return btoa(unescape(encodeURIComponent(password)))}
function saveAuth(){localStorage.guildAgendaAuth=JSON.stringify(auth)}
function updateAuthUi(){currentUser=auth.users.find(u=>u.username===auth.session)||null;$('logout').hidden=!currentUser;$('access').hidden=!(currentUser?.role==='admin');if(currentUser&&state.players.includes(currentUser.username)){state.current=currentUser.username;save()}}
function showLogin(){const first=!auth.users.length;$('loginTitle').textContent=first?'Criar administrador':'Entrar';$('loginHelp').textContent=first?'Primeiro acesso neste navegador: crie seu usuário administrador. Observação: esta camada ainda é local; autenticação segura online virá com backend.':'Entre com o usuário liberado pelo administrador deste navegador.';$('loginButton').textContent=first?'Criar admin':'Entrar';$('loginUser').value=first?'Murilo':'';$('loginPass').value='';$('loginDlg').showModal()}
$('loginForm').onsubmit=async e=>{e.preventDefault();const username=$('loginUser').value.trim(),password=$('loginPass').value;if(!username||!password)return;const hash=await passHash(password);if(!auth.users.length){auth.users.push({username,passwordHash:hash,role:'admin'});if(!state.players.includes(username))state.players.push(username);auth.session=username;saveAuth();save();$('loginDlg').close();updateAuthUi();render();toast('Administrador criado');return}const user=auth.users.find(u=>u.username===username&&u.passwordHash===hash);if(!user){toast('Usuário ou senha inválidos');return}auth.session=user.username;saveAuth();$('loginDlg').close();updateAuthUi();render();toast('Login efetuado')};
$('logout').onclick=()=>{auth.session=null;saveAuth();currentUser=null;updateAuthUi();showLogin()};
$('access').onclick=()=>{if(currentUser?.role!=='admin'){toast('Apenas administrador');return}renderUsers();$('accessDlg').showModal()};
function renderUsers(){$('usersList').innerHTML=auth.users.map(u=>`<div class="userrow"><div><b>${u.username}</b><small>${u.role==='admin'?'Administrador':'Usuário'}</small></div>${u.username===currentUser?.username?'<span class="sub">você</span>':`<button class="btn red" onclick="removeUser('${u.username.replaceAll("'","\\'")}')">Excluir</button>`}</div>`).join('')||'<p class="sub">Nenhum usuário.</p>'}
window.removeUser=username=>{if(!confirm(`Remover acesso de ${username}?`))return;auth.users=auth.users.filter(u=>u.username!==username);saveAuth();renderUsers();toast('Usuário removido')};
$('userForm').onsubmit=async e=>{e.preventDefault();const username=$('newUser').value.trim(),password=$('newPass').value;if(auth.users.some(u=>u.username===username)){toast('Usuário já existe');return}auth.users.push({username,passwordHash:await passHash(password),role:$('newRole').value});if(!state.players.includes(username))state.players.push(username);saveAuth();save();$('newUser').value='';$('newPass').value='';renderUsers();render();toast('Usuário adicionado')};
function initAuth(){if(auth.session)currentUser=auth.users.find(u=>u.username===auth.session)||null;updateAuthUi();if(!currentUser)showLogin()}
render();
initAuth();
